spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mobile_users?useSSL=false&serverTimezone=UTC
        username: root
        password: Prince74482@sql
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
